import { DEFAULT_SALES_PROCESS } from "../opportunities/salesProcess";
import {
  buildDefaultOppMappingSubtypes,
  buildDefaultOppMappingThemes,
} from "./oppMappingLibrary";
import type { OrgConfig } from "./types";
import { DEFAULT_CATALOG_FEATURES, DEFAULT_KPI_RULES } from "./types";

export const defaultConfig: OrgConfig = {
  version: 1,
  catalogFeatures: { ...DEFAULT_CATALOG_FEATURES },
  orgProfile: {
    name: "Powermap Vendor",
    description:
      "Éditeur B2B de cartographie d’influence et d’account planning. Nous aidons les équipes sales enterprise à qualifier les deals, mapper le pouvoir et prioriser les actions.",
    usps: [
      {
        id: "usp-org-1",
        label: "Account planning multi-opps",
        description:
          "Un plan unique par compte, relié à plusieurs opportunités et au process de qualification.",
        active: true,
        order: 1,
      },
      {
        id: "usp-org-2",
        label: "Power mapping + process",
        description:
          "Combinaison cartographie d’influence et scoring process (domaines / questions) dans le même outil.",
        active: true,
        order: 2,
      },
    ],
  },
  contactTypes: [
    {
      id: "EconomicBuyer",
      label: "Economic Buyer",
      color: "#7c3aed",
      active: true,
      order: 1,
    },
    {
      id: "Champion",
      label: "Champion",
      color: "#0f766e",
      active: true,
      order: 2,
    },
    {
      id: "Influencer",
      label: "Influencer",
      color: "#2563eb",
      active: true,
      order: 3,
    },
    {
      id: "Blocker",
      label: "Blocker",
      color: "#b91c1c",
      active: true,
      order: 4,
    },
    {
      id: "User",
      label: "User",
      color: "#6b7280",
      active: true,
      order: 5,
    },
    {
      id: "Procurement",
      label: "Procurement",
      color: "#b45309",
      active: true,
      order: 6,
    },
  ],
  solutions: [
    {
      id: "sol-platform",
      name: "Platform EU",
      code: "PLT",
      description:
        "Plateforme collaborative pour cartographier les comptes, les contacts d’influence et piloter l’account plan.",
      active: true,
      order: 1,
      modules: [
        {
          id: "mod-plt-core",
          label: "Core Platform",
          description: "Socle comptes, contacts, relations et canvas de carte.",
          usps: [
            {
              id: "usp-plt-core-1",
              label: "Carte live multi-acteurs",
              description:
                "Visualisation des relations d’influence en temps réel, filtrable par type de contact.",
              active: true,
              order: 1,
            },
          ],
          active: true,
          order: 1,
        },
        {
          id: "mod-plt-sso",
          label: "SSO / IAM",
          description: "Authentification entreprise (SAML / OIDC).",
          usps: [],
          active: true,
          order: 2,
        },
        {
          id: "mod-plt-api",
          label: "API & Connecteurs",
          description: "API REST et connecteurs CRM pour synchroniser le pipeline.",
          usps: [
            {
              id: "usp-plt-api-1",
              label: "Sync CRM bidirectionnelle",
              description:
                "Opportunités et contacts alignés avec le CRM sans double saisie.",
              active: true,
              order: 1,
            },
          ],
          active: true,
          order: 3,
        },
        {
          id: "mod-plt-analytics",
          label: "Analytics Add-on",
          description: "Tableaux de bord process et matrice des risques portefeuille.",
          usps: [],
          active: true,
          order: 4,
        },
      ],
    },
    {
      id: "sol-analytics",
      name: "Analytics Suite",
      code: "ANL",
      description:
        "Suite d’analyse pour mesurer la santé du pipeline et les goulots process.",
      active: true,
      order: 2,
      modules: [
        {
          id: "mod-anl-dash",
          label: "Dashboards",
          description: "KPI process pondérés et suivi des deals à risque.",
          usps: [],
          active: true,
          order: 1,
        },
        {
          id: "mod-anl-lake",
          label: "Data Lake",
          description: "Historisation des réponses process et outcomes.",
          usps: [],
          active: true,
          order: 2,
        },
        {
          id: "mod-anl-alerts",
          label: "Alerting",
          description: "Alertes sur domaines bloquants et close dates.",
          usps: [],
          active: true,
          order: 3,
        },
      ],
    },
    {
      id: "sol-support",
      name: "Premium Support",
      code: "SUP",
      description: "Accompagnement CSM et enablement sales sur le déploiement.",
      active: true,
      order: 3,
      modules: [
        {
          id: "mod-sup-gold",
          label: "Gold",
          description: "Support standard + revues trimestrielles.",
          usps: [],
          active: true,
          order: 1,
        },
        {
          id: "mod-sup-plat",
          label: "Platinum",
          description: "CSM dédié + ateliers process / power mapping.",
          usps: [],
          active: true,
          order: 2,
        },
      ],
    },
  ],
  competitors: [
    {
      id: "comp-altmap",
      name: "AltMap",
      description:
        "Concurrent historique focus org charts. Fort sur la visualisation, plus faible sur le process de qualification et l’account planning multi-opps.",
      active: true,
      order: 1,
      features: [
        {
          id: "cf-alt-chart",
          label: "Org chart interactif",
          description: "Cartographie hiérarchique soignée, export PowerPoint.",
          ourModuleId: "mod-plt-core",
          active: true,
          order: 1,
        },
        {
          id: "cf-alt-crm",
          label: "Connecteur Salesforce",
          description: "Sync contacts et comptes, pas d’opportunités multi-plans.",
          ourModuleId: "mod-plt-api",
          active: true,
          order: 2,
        },
      ],
    },
  ],
  oppVariables: [
    {
      id: "var-users",
      label: "Nb utilisateurs",
      kind: "number",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "var-licenses",
      label: "Nb licences",
      kind: "number",
      active: true,
      order: 2,
      defaultValue: 0,
    },
  ],
  directions: [
    { id: "dir-fr-fin", name: "Finance", active: true, order: 1 },
    { id: "dir-fr-ops", name: "Sales Ops", active: true, order: 2 },
    { id: "dir-fr-it", name: "IT", active: true, order: 3 },
    { id: "dir-de-tech", name: "Technology", active: true, order: 4 },
    { id: "dir-de-proc", name: "Procurement", active: true, order: 5 },
    { id: "dir-nova-sales", name: "Sales", active: true, order: 6 },
  ],
  sectors: [
    {
      id: "sec-industrie",
      name: "Industrie / Manufacturing",
      active: true,
      order: 1,
    },
    { id: "sec-tech", name: "Tech / SaaS", active: true, order: 2 },
    { id: "sec-services", name: "Services", active: true, order: 3 },
    { id: "sec-finance", name: "Banque / Assurance", active: true, order: 4 },
    { id: "sec-sante", name: "Santé / Pharma", active: true, order: 5 },
    { id: "sec-energie", name: "Énergie / Utilities", active: true, order: 6 },
    { id: "sec-retail", name: "Retail / Distribution", active: true, order: 7 },
    { id: "sec-public", name: "Secteur public", active: true, order: 8 },
  ],
  boCategories: [
    { id: "bocat-cost", label: "Réduction des coûts", active: true, order: 1 },
    { id: "bocat-risk", label: "Réduction des risques", active: true, order: 2 },
    { id: "bocat-growth", label: "Croissance", active: true, order: 3 },
    {
      id: "bocat-ops",
      label: "Efficacité opérationnelle",
      active: true,
      order: 4,
    },
    { id: "bocat-compliance", label: "Conformité", active: true, order: 5 },
    {
      id: "bocat-ux",
      label: "Expérience utilisateur",
      active: true,
      order: 6,
    },
    { id: "bocat-calc", label: "Paramètres de calcul", active: true, order: 7 },
  ],
  boFields: [
    // Réduction des coûts
    {
      id: "bo-cost-ops",
      label: "Réduire les coûts opérationnels",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "bo-cost-audits",
      label: "Diminuer les dépenses liées aux audits",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 2,
      defaultValue: 0,
    },
    {
      id: "bo-cost-noncompliance",
      label: "Réduire les coûts de non-conformité",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 3,
      defaultValue: 0,
    },
    // Réduction des risques
    {
      id: "bo-risk-cyber",
      label: "Réduire les cyberattaques provenant des tiers",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 4,
      defaultValue: 0,
    },
    {
      id: "bo-risk-reg",
      label: "Réduire le risque réglementaire",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 5,
      defaultValue: 0,
    },
    {
      id: "bo-risk-interrupt",
      label: "Réduire les interruptions d’activité",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 6,
      defaultValue: 0,
    },
    // Croissance
    {
      id: "bo-growth-clients",
      label: "Gagner davantage de clients",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 7,
      defaultValue: 0,
    },
    {
      id: "bo-growth-products",
      label: "Accélérer le lancement de nouveaux produits",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 8,
      defaultValue: 0,
    },
    {
      id: "bo-growth-markets",
      label: "Ouvrir de nouveaux marchés",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 9,
      defaultValue: 0,
    },
    // Efficacité opérationnelle
    {
      id: "bo-ops-delay",
      label: "Réduire les délais de traitement",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 10,
      defaultValue: 0,
    },
    {
      id: "bo-ops-productivity",
      label: "Augmenter la productivité des équipes",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 11,
      defaultValue: 0,
    },
    {
      id: "bo-ops-manual",
      label: "Éliminer les tâches manuelles",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 12,
      defaultValue: 0,
    },
    // Conformité
    {
      id: "bo-comp-nis2",
      label: "Être conforme à NIS2, DORA, CSRD, etc.",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 13,
      defaultValue: 0,
    },
    {
      id: "bo-comp-audits",
      label: "Réussir les audits",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 14,
      defaultValue: 0,
    },
    {
      id: "bo-comp-proofs",
      label: "Produire les preuves réglementaires plus rapidement",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 15,
      defaultValue: 0,
    },
    // Expérience utilisateur
    {
      id: "bo-ux-suppliers",
      label: "Améliorer la satisfaction des fournisseurs",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 16,
      defaultValue: 0,
    },
    {
      id: "bo-ux-friction",
      label: "Réduire les frictions dans les processus",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 17,
      defaultValue: 0,
    },
    {
      id: "bo-ux-adoption",
      label: "Augmenter le taux d’adoption de l’outil",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 18,
      defaultValue: 0,
    },
    // Paramètres de calcul
    {
      id: "oneTimeInvestment",
      label: "Investissement one-shot (€)",
      kind: "one_time",
      categoryId: "bocat-calc",
      active: true,
      order: 19,
      defaultValue: 0,
    },
    {
      id: "horizonYears",
      label: "Horizon (années)",
      kind: "horizon",
      categoryId: "bocat-calc",
      active: true,
      order: 20,
      defaultValue: 3,
    },
  ],
  processDomains: structuredClone(DEFAULT_SALES_PROCESS),
  oppMappingSubtypes: buildDefaultOppMappingSubtypes(),
  oppMappingThemes: buildDefaultOppMappingThemes(),
  riskMatrix: {
    processHighThreshold: 70,
    processLowThreshold: 35,
    pipelinePhases: [
      "Whitespace",
      "Discovery",
      "Solution Validation",
      "Negotiation",
    ],
    axisLabels: {
      processHigh: "Process élevé",
      processMid: "Process moyen",
      processLow: "Process faible",
      pipeline: "Opportunity Mapping",
    },
  },
  researchCriteria: [
    {
      id: "rc-ce",
      label: "Compelling Event",
      hint: "Identifier pourquoi le client doit agir maintenant — rapprocher des Compelling Events du catalogue admin quand c’est pertinent.",
      active: true,
      order: 1,
    },
    {
      id: "rc-initiatives",
      label: "Initiatives & programmes",
      hint: "Programmes digitaux, cloud, cyber, M&A, transformation en cours ou annoncés.",
      active: true,
      order: 2,
    },
    {
      id: "rc-decision",
      label: "Decision Criteria",
      hint: "Critères d’achat formels / informels probables pour ce type d’achat IT / B2B.",
      active: true,
      order: 3,
    },
    {
      id: "rc-competitor",
      label: "Concurrent en place",
      hint: "Solutions / éditeurs déjà présents ou mentionnés (stack, appels d’offres, partenariats).",
      active: true,
      order: 4,
    },
    {
      id: "rc-pressures",
      label: "Pressions (budget / réglementaire)",
      hint: "Contraintes budgétaires, conformité, audits, pressions board / marché.",
      active: true,
      order: 5,
    },
    {
      id: "rc-buyers",
      label: "Personas & décideurs",
      hint: "Identifier des personas / décideurs documentés publiquement (site, presse, LinkedIn public) — noms, titres, rôle probable — pour créer des contacts.",
      active: true,
      order: 6,
    },
    {
      id: "rc-news",
      label: "Actualités 6 mois",
      hint: "Actualité globale de l’entreprise sur les 6 derniers mois : faits marquants, presse positive et négative, utiles à un account plan.",
      active: true,
      order: 7,
    },
  ],
  compellingEvents: [
    {
      id: "ce-reg-deadline",
      label: "Échéance réglementaire / audit",
      description:
        "Obligation de conformité, audit, certification ou deadline légale qui force une décision d’achat.",
      active: true,
      order: 1,
    },
    {
      id: "ce-contract-renewal",
      label: "Renouvellement / fin de contrat",
      description:
        "Échéance de contrat en place (éditeur, MSP, licence) créant une fenêtre de décision.",
      active: true,
      order: 2,
    },
    {
      id: "ce-mna",
      label: "M&A / intégration post-acquisition",
      description:
        "Fusion, acquisition ou intégration de périmètres qui impose harmonisation des outils et process.",
      active: true,
      order: 3,
    },
    {
      id: "ce-digital-program",
      label: "Programme digital / cloud / cyber",
      description:
        "Initiative structurante (transformation digitale, migration cloud, cybersécurité) sponsorisée au COMEX.",
      active: true,
      order: 4,
    },
    {
      id: "ce-cost-pressure",
      label: "Pression coûts / productivité",
      description:
        "Objectif de réduction de coûts, productivité ou rationalisation du stack qui accélère le deal.",
      active: true,
      order: 5,
    },
    {
      id: "ce-churn-risk",
      label: "Risque churn / perte de clients",
      description:
        "Pression business liée à la rétention, à la qualité de service ou à la vision comptes.",
      active: true,
      order: 6,
    },
  ],
  oppPhases: [
    { id: "Whitespace", label: "Whitespace", kpiRole: "whitespace", active: true, order: 1 },
    { id: "Discovery", label: "Discovery", kpiRole: "pipeline", active: true, order: 2 },
    {
      id: "Solution Validation",
      label: "Solution Validation",
      kpiRole: "pipeline",
      active: true,
      order: 3,
    },
    { id: "Negotiation", label: "Negotiation", kpiRole: "pipeline", active: true, order: 4 },
    { id: "Closed Won", label: "Closed Won", kpiRole: "won", active: true, order: 5 },
    { id: "Closed Lost", label: "Closed Lost", kpiRole: "lost", active: true, order: 6 },
  ],
  oppKinds: [
    { id: "up", label: "Upsell", targetMode: "by_phase", active: true, order: 1 },
    { id: "cross", label: "Cross-sell", targetMode: "by_phase", active: true, order: 2 },
    { id: "renewal", label: "Renouvellement", targetMode: "renewal", active: true, order: 3 },
    {
      id: "new_in_group",
      label: "Nouveau compte dans le groupe",
      targetMode: "by_phase",
      active: true,
      order: 4,
    },
    { id: "prospect", label: "Prospect", targetMode: "by_phase", active: true, order: 5 },
  ],
  commercialStatuses: [
    { id: "Client", label: "Client", active: true, order: 1 },
    { id: "Prospect", label: "Prospect", active: true, order: 2 },
    { id: "Partner", label: "Partenaire", active: true, order: 3 },
    { id: "Other", label: "Autre", active: true, order: 4 },
  ],
  accountSizes: [
    { id: "1-1000", label: "Jusqu’à 1 000", active: true, order: 1 },
    { id: "1001-2500", label: "1 001 – 2 500", active: true, order: 2 },
    { id: "2501-5000", label: "2 501 – 5 000", active: true, order: 3 },
    { id: "5001-10000", label: "5 001 – 10 000", active: true, order: 4 },
    { id: "10000+", label: "10 000+", active: true, order: 5 },
  ],
  kpiRules: { ...DEFAULT_KPI_RULES },
};
