import {
  buildDefaultOppPhases,
  DEFAULT_SALES_PROCESS,
} from "../opportunities/salesProcess";
import {
  buildDefaultOppMappingSubtypes,
  buildDefaultOppMappingThemes,
} from "./oppMappingLibrary";
import type { OrgConfig, OppKindDef, OppPhaseDef } from "./types";
import {
  DEFAULT_CATALOG_FEATURES,
  DEFAULT_KPI_RULES,
  DEFAULT_OPP_KINDS,
} from "./types";

/**
 * Paramètres d’usine : référentiels sales génériques prêts à l’emploi.
 * L’org peut tout modifier / désactiver ensuite dans Settings.
 * Identité vendeur (profil) et catalogue offre restent vides (spécifiques client).
 */
export const defaultConfig: OrgConfig = {
  version: 1,
  catalogFeatures: { ...DEFAULT_CATALOG_FEATURES },
  orgProfile: {
    name: "",
    description: "",
    usps: [],
  },
  contactTypes: [
    {
      id: "EconomicBuyer",
      label: "Economic Buyer",
      color: "#7c3aed",
      active: true,
      order: 1,
    },
    {
      id: "Champion",
      label: "Champion",
      color: "#0f766e",
      active: true,
      order: 2,
    },
    {
      id: "Influencer",
      label: "Influencer",
      color: "#2563eb",
      active: true,
      order: 3,
    },
    {
      id: "Blocker",
      label: "Blocker",
      color: "#b91c1c",
      active: true,
      order: 4,
    },
    {
      id: "User",
      label: "User",
      color: "#6b7280",
      active: true,
      order: 5,
    },
    {
      id: "Procurement",
      label: "Procurement",
      color: "#b45309",
      active: true,
      order: 6,
    },
  ],
  /** Offre produit : à configurer par l’org. */
  solutions: [],
  competitors: [],
  oppVariables: [
    {
      id: "var-users",
      label: "Nb utilisateurs",
      kind: "number",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "var-licenses",
      label: "Nb licences",
      kind: "number",
      active: true,
      order: 2,
      defaultValue: 0,
    },
  ],
  personae: [
    { id: "persona-dg", name: "DG / Economic Buyer", active: true, order: 1 },
    { id: "persona-cfo", name: "CFO / Finance Buyer", active: true, order: 2 },
    { id: "persona-cio", name: "CIO / IT Buyer", active: true, order: 3 },
    { id: "persona-coo", name: "COO / Operations", active: true, order: 4 },
    { id: "persona-chro", name: "CHRO / HR Buyer", active: true, order: 5 },
    { id: "persona-cpo", name: "CPO / Procurement", active: true, order: 6 },
    {
      id: "persona-champion",
      name: "Champion métier",
      active: true,
      order: 7,
    },
  ],
  sectors: [
    {
      id: "sec-industrie",
      name: "Industrie / Manufacturing",
      active: true,
      order: 1,
    },
    { id: "sec-tech", name: "Tech / SaaS", active: true, order: 2 },
    { id: "sec-services", name: "Services", active: true, order: 3 },
    { id: "sec-finance", name: "Banque / Assurance", active: true, order: 4 },
    { id: "sec-sante", name: "Santé / Pharma", active: true, order: 5 },
    { id: "sec-energie", name: "Énergie / Utilities", active: true, order: 6 },
    { id: "sec-retail", name: "Retail / Distribution", active: true, order: 7 },
    { id: "sec-public", name: "Secteur public", active: true, order: 8 },
  ],
  boCategories: [
    {
      id: "bocat-calc",
      label: "Paramètres ROI",
      active: true,
      order: 1,
    },
  ],
  boFields: [
    {
      id: "oneTimeInvestment",
      label: "Investissement one-shot (€)",
      kind: "one_time",
      categoryId: "bocat-calc",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "horizonYears",
      label: "Horizon (années)",
      kind: "horizon",
      categoryId: "bocat-calc",
      active: true,
      order: 2,
      defaultValue: 3,
    },
  ],
  processDomains: structuredClone(DEFAULT_SALES_PROCESS),
  oppMappingSubtypes: buildDefaultOppMappingSubtypes(),
  oppMappingThemes: buildDefaultOppMappingThemes(),
  riskMatrix: {
    processHighThreshold: 70,
    processLowThreshold: 35,
    pipelinePhases: [],
    axisLabels: {
      processHigh: "Process élevé",
      processMid: "Process moyen",
      processLow: "Process faible",
      pipeline: "Opportunity Mapping",
    },
  },
  compellingEvents: [
    {
      id: "ce-reg-deadline",
      label: "Échéance réglementaire / audit",
      description:
        "Obligation de conformité, audit, certification ou deadline légale qui force une décision d’achat.",
      active: true,
      order: 1,
    },
    {
      id: "ce-contract-renewal",
      label: "Renouvellement / fin de contrat",
      description:
        "Échéance de contrat en place (éditeur, MSP, licence) créant une fenêtre de décision.",
      active: true,
      order: 2,
    },
    {
      id: "ce-mna",
      label: "M&A / intégration post-acquisition",
      description:
        "Fusion, acquisition ou intégration de périmètres qui impose harmonisation des outils et process.",
      active: true,
      order: 3,
    },
    {
      id: "ce-digital-program",
      label: "Programme digital / cloud / cyber",
      description:
        "Initiative structurante (transformation digitale, migration cloud, cybersécurité) sponsorisée au COMEX.",
      active: true,
      order: 4,
    },
    {
      id: "ce-cost-pressure",
      label: "Pression coûts / productivité",
      description:
        "Objectif de réduction de coûts, productivité ou rationalisation du stack qui accélère le deal.",
      active: true,
      order: 5,
    },
    {
      id: "ce-churn-risk",
      label: "Risque churn / perte de clients",
      description:
        "Pression business liée à la rétention, à la qualité de service ou à la vision comptes.",
      active: true,
      order: 6,
    },
  ],
  projectLeverFamilies: [
    {
      id: "plf-strategy",
      label: "Enjeu stratégique / business",
      description: "Le projet répond à un enjeu métier ou de croissance identifiable.",
      active: true,
      order: 1,
    },
    {
      id: "plf-internal",
      label: "Dynamique interne",
      description: "Des forces internes poussent à structurer un projet.",
      active: true,
      order: 2,
    },
    {
      id: "plf-external",
      label: "Contexte externe",
      description: "Des facteurs externes créent ou accélèrent le besoin de projet.",
      active: true,
      order: 3,
    },
    {
      id: "plf-capacity",
      label: "Capacité à investir",
      description: "Le client a (ou cherche) les moyens de financer un projet.",
      active: true,
      order: 4,
    },
  ],
  projectLevers: [
    {
      id: "pl-growth",
      familyId: "plf-strategy",
      label: "Objectif de croissance / part de marché",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pl-efficiency",
      familyId: "plf-strategy",
      label: "Enjeu de productivité / coûts",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pl-risk",
      familyId: "plf-strategy",
      label: "Enjeu de risque / conformité métier",
      description: "",
      active: true,
      order: 3,
    },
    {
      id: "pl-sponsor",
      familyId: "plf-internal",
      label: "Sponsor identifié (direction / métier)",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pl-initiative",
      familyId: "plf-internal",
      label: "Initiative / programme déjà nommé en interne",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pl-pain",
      familyId: "plf-internal",
      label: "Douleur opérationnelle récurrente remontée",
      description: "",
      active: true,
      order: 3,
    },
    {
      id: "pl-market",
      familyId: "plf-external",
      label: "Pression concurrentielle / marché",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pl-regulation",
      familyId: "plf-external",
      label: "Contrainte réglementaire ou audit",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pl-tech",
      familyId: "plf-external",
      label: "Obsolescence / dette technique du stack actuel",
      description: "",
      active: true,
      order: 3,
    },
    {
      id: "pl-budget",
      familyId: "plf-capacity",
      label: "Budget ou enveloppe évoquée",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pl-timeline",
      familyId: "plf-capacity",
      label: "Fenêtre de décision / calendrier projet",
      description: "",
      active: true,
      order: 2,
    },
  ],
  projectProblemFamilies: [
    {
      id: "ppf-ops",
      label: "Opérationnel / efficacité",
      description: "Le client cherche à corriger un frein d’exécution.",
      active: true,
      order: 1,
    },
    {
      id: "ppf-risk",
      label: "Risque & conformité",
      description: "Exposition réglementaire, cyber ou de continuité.",
      active: true,
      order: 2,
    },
    {
      id: "ppf-growth",
      label: "Croissance & compétitivité",
      description: "Enjeu de développement, part de marché ou offre.",
      active: true,
      order: 3,
    },
    {
      id: "ppf-visibility",
      label: "Visibilité & pilotage",
      description: "Manque de données, de preuves ou de gouvernance.",
      active: true,
      order: 4,
    },
  ],
  projectProblems: [
    {
      id: "pp-manual",
      familyId: "ppf-ops",
      label: "Process trop manuels / lents",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pp-cost",
      familyId: "ppf-ops",
      label: "Coûts opérationnels trop élevés",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pp-silo",
      familyId: "ppf-ops",
      label: "Outils / équipes en silos",
      description: "",
      active: true,
      order: 3,
    },
    {
      id: "pp-compliance",
      familyId: "ppf-risk",
      label: "Non-conformité réglementaire (NIS2, DORA, CSRD…)",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pp-audit",
      familyId: "ppf-risk",
      label: "Difficulté à produire preuves / réussir audits",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pp-cyber",
      familyId: "ppf-risk",
      label: "Risque cyber / tiers non maîtrisé",
      description: "",
      active: true,
      order: 3,
    },
    {
      id: "pp-clients",
      familyId: "ppf-growth",
      label: "Perte de clients / qualité de service",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pp-time-to-market",
      familyId: "ppf-growth",
      label: "Time-to-market trop long",
      description: "",
      active: true,
      order: 2,
    },
    {
      id: "pp-data",
      familyId: "ppf-visibility",
      label: "Données non fiables ou indisponibles",
      description: "",
      active: true,
      order: 1,
    },
    {
      id: "pp-pilotage",
      familyId: "ppf-visibility",
      label: "Manque de visibilité / pilotage COMEX",
      description: "",
      active: true,
      order: 2,
    },
  ],
  personalMotivations: [
    {
      id: "pm-career",
      label: "Carrière / promotion",
      description: "Le projet sert une trajectoire personnelle.",
      polarity: "advance",
      active: true,
      order: 1,
    },
    {
      id: "pm-manager-obj",
      label: "Objectif fixé par le manager",
      description: "KPI ou mission assignée explicitement.",
      polarity: "advance",
      active: true,
      order: 2,
    },
    {
      id: "pm-bonus",
      label: "Bonus / variable",
      description: "Rémunération liée à la réussite du projet.",
      polarity: "advance",
      active: true,
      order: 3,
    },
    {
      id: "pm-visibility",
      label: "Visibilité / reconnaissance",
      description: "Exposition COMEX, peer recognition.",
      polarity: "advance",
      active: true,
      order: 4,
    },
    {
      id: "pm-job-security",
      label: "Sécuriser son poste / périmètre",
      description: "Le projet renforce son rôle.",
      polarity: "advance",
      active: true,
      order: 5,
    },
    {
      id: "pm-political-risk",
      label: "Risque politique / perte de face",
      description: "Avancer expose à un échec visible.",
      polarity: "retreat",
      active: true,
      order: 1,
    },
    {
      id: "pm-overload",
      label: "Charge déjà saturée",
      description: "Pas de bande passante pour porter le projet.",
      polarity: "retreat",
      active: true,
      order: 2,
    },
    {
      id: "pm-change-fear",
      label: "Peur du changement / de l’outil",
      description: "Résistance au nouveau process ou stack.",
      polarity: "retreat",
      active: true,
      order: 3,
    },
    {
      id: "pm-other-priority",
      label: "Autre priorité conflictuelle",
      description: "Un autre chantier passe avant.",
      polarity: "retreat",
      active: true,
      order: 4,
    },
    {
      id: "pm-turf",
      label: "Protection de budget / territoire",
      description: "Le projet menace un périmètre contrôlé.",
      polarity: "retreat",
      active: true,
      order: 5,
    },
  ],
  whyNowObjectives: [
    {
      id: "wno-cost-pct",
      label: "Réduction mesurable des coûts",
      description: "Saisir le % de réduction ciblé.",
      kind: "quantitative",
      valueUnit: "percent",
      active: true,
      order: 1,
    },
    {
      id: "wno-cycle-time",
      label: "Réduction des délais / cycle time",
      description: "Saisir le gain en jours.",
      kind: "quantitative",
      valueUnit: "days",
      active: true,
      order: 2,
    },
    {
      id: "wno-zero-ncr",
      label: "Nombre de non-conformités critiques",
      description: "Saisir la cible (ex. 0).",
      kind: "quantitative",
      valueUnit: "number",
      active: true,
      order: 3,
    },
    {
      id: "wno-productivity",
      label: "Gain de productivité / capacité",
      description: "Saisir le % de gain.",
      kind: "quantitative",
      valueUnit: "percent",
      active: true,
      order: 4,
    },
    {
      id: "wno-risk-euro",
      label: "Réduction du risque chiffré",
      description: "Saisir le montant d’exposition évité (€ / an).",
      kind: "quantitative",
      valueUnit: "euro",
      active: true,
      order: 5,
    },
    {
      id: "wno-fte",
      label: "Charge manuelle évitée",
      description: "Saisir les ETP libérés.",
      kind: "quantitative",
      valueUnit: "fte",
      active: true,
      order: 6,
    },
    {
      id: "wno-comex",
      label: "Rassurer le COMEX / direction",
      description: "Alignement politique et confiance décideurs.",
      kind: "qualitative",
      valueUnit: "number",
      active: true,
      order: 1,
    },
    {
      id: "wno-audits",
      label: "Fiabiliser les audits / preuves",
      description: "Capacité à démontrer la conformité.",
      kind: "qualitative",
      valueUnit: "number",
      active: true,
      order: 2,
    },
    {
      id: "wno-workload",
      label: "Réduire la charge / friction équipes",
      description: "Soulager ops, compliance, IT…",
      kind: "qualitative",
      valueUnit: "number",
      active: true,
      order: 3,
    },
    {
      id: "wno-visibility",
      label: "Améliorer la visibilité / pilotage",
      description: "Tableaux de bord, gouvernance, reporting.",
      kind: "qualitative",
      valueUnit: "number",
      active: true,
      order: 4,
    },
    {
      id: "wno-trust",
      label: "Restaurer confiance clients / partenaires",
      description: "Image, qualité de service, rétention.",
      kind: "qualitative",
      valueUnit: "number",
      active: true,
      order: 5,
    },
  ],
  inactionLeverFamilies: [
    {
      id: "ilf-productivity",
      label: "Gain productivité",
      description:
        "Temps homme perdu ou gaspillé — matérialisé en € via le coût ETP.",
      active: true,
      order: 1,
    },
    {
      id: "ilf-gain",
      label: "Gain CA",
      description:
        "Chiffre d’affaires en plus (ou non réalisé) si on agit / n’agit pas.",
      active: true,
      order: 2,
    },
    {
      id: "ilf-avoided",
      label: "Coût évité",
      description:
        "Risques et pertes qu’on évite en agissant (impact × fréquence attendue).",
      active: true,
      order: 3,
    },
    {
      id: "ilf-capability",
      label: "Capacité",
      description:
        "Options stratégiques : faire ce qui était impossible, absorber la croissance.",
      active: false,
      order: 4,
    },
    {
      id: "ilf-personal",
      label: "Leviers personnels",
      description:
        "Drivers du porteur — souvent décisifs, parfois peu monétisables.",
      active: false,
      order: 5,
    },
  ],
  inactionLevers: [
    {
      id: "il-productivity",
      valueKind: "productivity",
      familyId: "ilf-productivity",
      label: "Temps improductif / rework",
      description: "Double saisie, reprises, files d’attente, réunions inutiles.",
      active: true,
      order: 1,
    },
    {
      id: "il-cost-time",
      valueKind: "productivity",
      familyId: "ilf-productivity",
      label: "Charge opérationnelle évitable",
      description: "Faire le même travail avec moins d’ETP ou moins d’heures.",
      active: true,
      order: 2,
    },
    {
      id: "il-revenue",
      valueKind: "revenue",
      familyId: "ilf-gain",
      label: "Chiffre d’affaires",
      description:
        "CA annuel en jeu — par défaut : CA actuel du client × hausse %.",
      formula: {
        enabled: true,
        inputs: [{ id: "revenueEur" }, { id: "upliftPct" }],
        operators: ["%"],
      },
      active: true,
      order: 1,
    },
    {
      id: "il-cash",
      valueKind: "revenue",
      familyId: "ilf-gain",
      label: "Trésorerie / BFR",
      description: "Effet cash (délais, stocks) exprimé en € / an.",
      formula: null,
      active: true,
      order: 2,
    },
    {
      id: "il-reg-risk",
      valueKind: "avoided",
      familyId: "ilf-avoided",
      label: "Risque réglementaire",
      description: "Sanction, non-conformité — impact € × fréquence attendue / an.",
      active: true,
      order: 1,
    },
    {
      id: "il-ops-risk",
      valueKind: "avoided",
      familyId: "ilf-avoided",
      label: "Risque opérationnel",
      description: "Panne, incident, perte de données — impact × occurrences.",
      active: true,
      order: 2,
    },
    {
      id: "il-commercial-risk",
      valueKind: "avoided",
      familyId: "ilf-avoided",
      label: "Risque commercial",
      description: "Perte de contrat / client clé — impact × vraisemblance annuelle.",
      active: true,
      order: 3,
    },
    {
      id: "il-human-risk",
      valueKind: "avoided",
      familyId: "ilf-avoided",
      label: "Risque humain",
      description: "Départ clé, usure — coût de remplacement × fréquence.",
      active: true,
      order: 4,
    },
    {
      id: "il-impossible",
      valueKind: "revenue",
      familyId: "ilf-capability",
      label: "Faire ce qui était impossible",
      description: "Nouveau marché / offre — CA optionnel ouvert par le projet.",
      active: true,
      order: 1,
    },
    {
      id: "il-absorb",
      valueKind: "productivity",
      familyId: "ilf-capability",
      label: "Absorber la croissance",
      description: "Sans outillage : recruter (temps / ETP) pour le même volume.",
      active: true,
      order: 2,
    },
    {
      id: "il-credibility",
      valueKind: "avoided",
      familyId: "ilf-personal",
      label: "Crédibilité du porteur",
      description: "Souvent narratif ; monétisez seulement si un enjeu € est clair.",
      active: true,
      order: 1,
    },
    {
      id: "il-workload",
      valueKind: "productivity",
      familyId: "ilf-personal",
      label: "Charge du porteur",
      description: "Bande passante du sponsor — temps ETP.",
      active: true,
      order: 2,
    },
  ],
  oppPhases: buildDefaultOppPhases() as OppPhaseDef[],
  oppKinds: structuredClone(DEFAULT_OPP_KINDS) as OppKindDef[],
  commercialStatuses: [
    { id: "Client", label: "Client", active: true, order: 1 },
    { id: "Prospect", label: "Prospect", active: true, order: 2 },
    { id: "Partner", label: "Partenaire", active: true, order: 3 },
    { id: "Concurrent", label: "Concurrent", active: true, order: 4 },
  ],
  accountSizes: [
    { id: "1-1000", label: "Jusqu’à 1 000", active: true, order: 1 },
    { id: "1001-2500", label: "1 001 – 2 500", active: true, order: 2 },
    { id: "2501-5000", label: "2 501 – 5 000", active: true, order: 3 },
    { id: "5001-10000", label: "5 001 – 10 000", active: true, order: 4 },
    { id: "10000+", label: "10 000+", active: true, order: 5 },
  ],
  kpiRules: { ...DEFAULT_KPI_RULES },
};
