import {
  buildDefaultOppPhases,
  DEFAULT_SALES_PROCESS,
} from "../opportunities/salesProcess";
import {
  buildDefaultOppMappingSubtypes,
  buildDefaultOppMappingThemes,
} from "./oppMappingLibrary";
import type { OrgConfig, OppKindDef, OppPhaseDef } from "./types";
import {
  DEFAULT_CATALOG_FEATURES,
  DEFAULT_KPI_RULES,
  DEFAULT_OPP_KINDS,
} from "./types";

/**
 * Paramètres d’usine : référentiels sales génériques prêts à l’emploi.
 * L’org peut tout modifier / désactiver ensuite dans Settings.
 * Identité vendeur (profil) et catalogue offre restent vides (spécifiques client).
 */
export const defaultConfig: OrgConfig = {
  version: 1,
  catalogFeatures: { ...DEFAULT_CATALOG_FEATURES },
  orgProfile: {
    name: "",
    description: "",
    usps: [],
  },
  contactTypes: [
    {
      id: "EconomicBuyer",
      label: "Economic Buyer",
      color: "#7c3aed",
      active: true,
      order: 1,
    },
    {
      id: "Champion",
      label: "Champion",
      color: "#0f766e",
      active: true,
      order: 2,
    },
    {
      id: "Influencer",
      label: "Influencer",
      color: "#2563eb",
      active: true,
      order: 3,
    },
    {
      id: "Blocker",
      label: "Blocker",
      color: "#b91c1c",
      active: true,
      order: 4,
    },
    {
      id: "User",
      label: "User",
      color: "#6b7280",
      active: true,
      order: 5,
    },
    {
      id: "Procurement",
      label: "Procurement",
      color: "#b45309",
      active: true,
      order: 6,
    },
  ],
  /** Offre produit : à configurer par l’org. */
  solutions: [],
  competitors: [],
  oppVariables: [
    {
      id: "var-users",
      label: "Nb utilisateurs",
      kind: "number",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "var-licenses",
      label: "Nb licences",
      kind: "number",
      active: true,
      order: 2,
      defaultValue: 0,
    },
  ],
  personae: [
    { id: "persona-dg", name: "DG / Economic Buyer", active: true, order: 1 },
    { id: "persona-cfo", name: "CFO / Finance Buyer", active: true, order: 2 },
    { id: "persona-cio", name: "CIO / IT Buyer", active: true, order: 3 },
    { id: "persona-coo", name: "COO / Operations", active: true, order: 4 },
    { id: "persona-chro", name: "CHRO / HR Buyer", active: true, order: 5 },
    { id: "persona-cpo", name: "CPO / Procurement", active: true, order: 6 },
    {
      id: "persona-champion",
      name: "Champion métier",
      active: true,
      order: 7,
    },
  ],
  sectors: [
    {
      id: "sec-industrie",
      name: "Industrie / Manufacturing",
      active: true,
      order: 1,
    },
    { id: "sec-tech", name: "Tech / SaaS", active: true, order: 2 },
    { id: "sec-services", name: "Services", active: true, order: 3 },
    { id: "sec-finance", name: "Banque / Assurance", active: true, order: 4 },
    { id: "sec-sante", name: "Santé / Pharma", active: true, order: 5 },
    { id: "sec-energie", name: "Énergie / Utilities", active: true, order: 6 },
    { id: "sec-retail", name: "Retail / Distribution", active: true, order: 7 },
    { id: "sec-public", name: "Secteur public", active: true, order: 8 },
  ],
  boCategories: [
    { id: "bocat-cost", label: "Réduction des coûts", active: true, order: 1 },
    { id: "bocat-risk", label: "Réduction des risques", active: true, order: 2 },
    { id: "bocat-growth", label: "Croissance", active: true, order: 3 },
    {
      id: "bocat-ops",
      label: "Efficacité opérationnelle",
      active: true,
      order: 4,
    },
    { id: "bocat-compliance", label: "Conformité", active: true, order: 5 },
    {
      id: "bocat-ux",
      label: "Expérience utilisateur",
      active: true,
      order: 6,
    },
    { id: "bocat-calc", label: "Paramètres de calcul", active: true, order: 7 },
  ],
  boFields: [
    {
      id: "bo-cost-ops",
      label: "Réduire les coûts opérationnels",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 1,
      defaultValue: 0,
    },
    {
      id: "bo-cost-audits",
      label: "Diminuer les dépenses liées aux audits",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 2,
      defaultValue: 0,
    },
    {
      id: "bo-cost-noncompliance",
      label: "Réduire les coûts de non-conformité",
      kind: "annual_benefit",
      categoryId: "bocat-cost",
      active: true,
      order: 3,
      defaultValue: 0,
    },
    {
      id: "bo-risk-cyber",
      label: "Réduire les cyberattaques provenant des tiers",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 4,
      defaultValue: 0,
    },
    {
      id: "bo-risk-reg",
      label: "Réduire le risque réglementaire",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 5,
      defaultValue: 0,
    },
    {
      id: "bo-risk-interrupt",
      label: "Réduire les interruptions d’activité",
      kind: "annual_benefit",
      categoryId: "bocat-risk",
      active: true,
      order: 6,
      defaultValue: 0,
    },
    {
      id: "bo-growth-clients",
      label: "Gagner davantage de clients",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 7,
      defaultValue: 0,
    },
    {
      id: "bo-growth-products",
      label: "Accélérer le lancement de nouveaux produits",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 8,
      defaultValue: 0,
    },
    {
      id: "bo-growth-markets",
      label: "Ouvrir de nouveaux marchés",
      kind: "annual_benefit",
      categoryId: "bocat-growth",
      active: true,
      order: 9,
      defaultValue: 0,
    },
    {
      id: "bo-ops-delay",
      label: "Réduire les délais de traitement",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 10,
      defaultValue: 0,
    },
    {
      id: "bo-ops-productivity",
      label: "Augmenter la productivité des équipes",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 11,
      defaultValue: 0,
    },
    {
      id: "bo-ops-manual",
      label: "Éliminer les tâches manuelles",
      kind: "annual_benefit",
      categoryId: "bocat-ops",
      active: true,
      order: 12,
      defaultValue: 0,
    },
    {
      id: "bo-comp-nis2",
      label: "Être conforme à NIS2, DORA, CSRD, etc.",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 13,
      defaultValue: 0,
    },
    {
      id: "bo-comp-audits",
      label: "Réussir les audits",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 14,
      defaultValue: 0,
    },
    {
      id: "bo-comp-proofs",
      label: "Produire les preuves réglementaires plus rapidement",
      kind: "annual_benefit",
      categoryId: "bocat-compliance",
      active: true,
      order: 15,
      defaultValue: 0,
    },
    {
      id: "bo-ux-suppliers",
      label: "Améliorer la satisfaction des fournisseurs",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 16,
      defaultValue: 0,
    },
    {
      id: "bo-ux-friction",
      label: "Réduire les frictions dans les processus",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 17,
      defaultValue: 0,
    },
    {
      id: "bo-ux-adoption",
      label: "Augmenter le taux d’adoption de l’outil",
      kind: "annual_benefit",
      categoryId: "bocat-ux",
      active: true,
      order: 18,
      defaultValue: 0,
    },
    {
      id: "oneTimeInvestment",
      label: "Investissement one-shot (€)",
      kind: "one_time",
      categoryId: "bocat-calc",
      active: true,
      order: 19,
      defaultValue: 0,
    },
    {
      id: "horizonYears",
      label: "Horizon (années)",
      kind: "horizon",
      categoryId: "bocat-calc",
      active: true,
      order: 20,
      defaultValue: 3,
    },
  ],
  processDomains: structuredClone(DEFAULT_SALES_PROCESS),
  oppMappingSubtypes: buildDefaultOppMappingSubtypes(),
  oppMappingThemes: buildDefaultOppMappingThemes(),
  riskMatrix: {
    processHighThreshold: 70,
    processLowThreshold: 35,
    pipelinePhases: [],
    axisLabels: {
      processHigh: "Process élevé",
      processMid: "Process moyen",
      processLow: "Process faible",
      pipeline: "Opportunity Mapping",
    },
  },
  compellingEvents: [
    {
      id: "ce-reg-deadline",
      label: "Échéance réglementaire / audit",
      description:
        "Obligation de conformité, audit, certification ou deadline légale qui force une décision d’achat.",
      active: true,
      order: 1,
    },
    {
      id: "ce-contract-renewal",
      label: "Renouvellement / fin de contrat",
      description:
        "Échéance de contrat en place (éditeur, MSP, licence) créant une fenêtre de décision.",
      active: true,
      order: 2,
    },
    {
      id: "ce-mna",
      label: "M&A / intégration post-acquisition",
      description:
        "Fusion, acquisition ou intégration de périmètres qui impose harmonisation des outils et process.",
      active: true,
      order: 3,
    },
    {
      id: "ce-digital-program",
      label: "Programme digital / cloud / cyber",
      description:
        "Initiative structurante (transformation digitale, migration cloud, cybersécurité) sponsorisée au COMEX.",
      active: true,
      order: 4,
    },
    {
      id: "ce-cost-pressure",
      label: "Pression coûts / productivité",
      description:
        "Objectif de réduction de coûts, productivité ou rationalisation du stack qui accélère le deal.",
      active: true,
      order: 5,
    },
    {
      id: "ce-churn-risk",
      label: "Risque churn / perte de clients",
      description:
        "Pression business liée à la rétention, à la qualité de service ou à la vision comptes.",
      active: true,
      order: 6,
    },
  ],
  oppPhases: buildDefaultOppPhases() as OppPhaseDef[],
  oppKinds: structuredClone(DEFAULT_OPP_KINDS) as OppKindDef[],
  commercialStatuses: [
    { id: "Client", label: "Client", active: true, order: 1 },
    { id: "Prospect", label: "Prospect", active: true, order: 2 },
    { id: "Partner", label: "Partenaire", active: true, order: 3 },
    { id: "Concurrent", label: "Concurrent", active: true, order: 4 },
  ],
  accountSizes: [
    { id: "1-1000", label: "Jusqu’à 1 000", active: true, order: 1 },
    { id: "1001-2500", label: "1 001 – 2 500", active: true, order: 2 },
    { id: "2501-5000", label: "2 501 – 5 000", active: true, order: 3 },
    { id: "5001-10000", label: "5 001 – 10 000", active: true, order: 4 },
    { id: "10000+", label: "10 000+", active: true, order: 5 },
  ],
  kpiRules: { ...DEFAULT_KPI_RULES },
};
